rm(list=ls())#删除目前所有的变量

library(foreign)
library(wesanderson)
library(psych)
library(pheatmap)
library(ade4)
library(readxl)
library(ggplot2)
library(Hmisc)

#模型构建：跨地区的多变量表征相似性矩阵（国家尺度，意间-时间-空间维度）
##以1998年老年人心理健康为例
CLHLSdata <- read_excel(".../mentalhealth_cross_region_1998.xlsx")
CLHLSdata <- as.data.frame(CLHLSdata)
mentalhealth<- CLHLSdata[c(1:7),c(2:23)]
mentalhealth<- as.data.frame(mentalhealth)
mentalhealth_1.dists <- dist(mentalhealth[,1])
mentalhealth_2.dists <- dist(mentalhealth[,2])
mentalhealth_3.dists <- dist(mentalhealth[,3])
mentalhealth_4.dists <- dist(mentalhealth[,4])
mentalhealth_5.dists <- dist(mentalhealth[,5])
mentalhealth_6.dists <- dist(mentalhealth[,6])
mentalhealth_7.dists <- dist(mentalhealth[,7])
mentalhealth_8.dists <- dist(mentalhealth[,8])
mentalhealth_9.dists <- dist(mentalhealth[,9])
mentalhealth_10.dists <- dist(mentalhealth[,10])
mentalhealth_11.dists <- dist(mentalhealth[,11])
mentalhealth_12.dists <- dist(mentalhealth[,12])
mentalhealth_13.dists <- dist(mentalhealth[,13])
mentalhealth_14.dists <- dist(mentalhealth[,14])
mentalhealth_15.dists <- dist(mentalhealth[,15])
mentalhealth_16.dists <- dist(mentalhealth[,16])
mentalhealth_17.dists <- dist(mentalhealth[,17])
mentalhealth_18.dists <- dist(mentalhealth[,18])
mentalhealth_19.dists <- dist(mentalhealth[,19])
mentalhealth_20.dists <- dist(mentalhealth[,20])
mentalhealth_21.dists <- dist(mentalhealth[,21])
mentalhealth_22.dists <- dist(mentalhealth[,22])
a1<-as.matrix(mentalhealth_1.dists)
a2<-as.matrix(mentalhealth_2.dists)
a3<-as.matrix(mentalhealth_3.dists)
a4<-as.matrix(mentalhealth_4.dists)
a5<-as.matrix(mentalhealth_5.dists)
a6<-as.matrix(mentalhealth_6.dists)
a7<-as.matrix(mentalhealth_7.dists)
a8<-as.matrix(mentalhealth_8.dists)
a9<-as.matrix(mentalhealth_9.dists)
a10<-as.matrix(mentalhealth_10.dists)
a11<-as.matrix(mentalhealth_11.dists)
a12<-as.matrix(mentalhealth_12.dists)
a13<-as.matrix(mentalhealth_13.dists)
a14<-as.matrix(mentalhealth_14.dists)
a15<-as.matrix(mentalhealth_15.dists)
a16<-as.matrix(mentalhealth_16.dists)
a17<-as.matrix(mentalhealth_17.dists)
a18<-as.matrix(mentalhealth_18.dists)
a19<-as.matrix(mentalhealth_19.dists)
a20<-as.matrix(mentalhealth_20.dists)
a21<-as.matrix(mentalhealth_21.dists)
a22<-as.matrix(mentalhealth_22.dists)
a1<-1-(a1-min(a1))/(max(a1)-min(a1))
a2<-1-(a2-min(a2))/(max(a2)-min(a2))
a3<-1-(a3-min(a3))/(max(a3)-min(a3))
a4<-1-(a4-min(a4))/(max(a4)-min(a4))
a5<-1-(a5-min(a5))/(max(a5)-min(a5))
a6<-1-(a6-min(a6))/(max(a6)-min(a6))
a7<-1-(a7-min(a7))/(max(a7)-min(a7))
a8<-1-(a8-min(a8))/(max(a8)-min(a8))
a9<-1-(a9-min(a9))/(max(a9)-min(a9))
a10<-1-(a10-min(a10))/(max(a10)-min(a10))
a11<-1-(a11-min(a11))/(max(a11)-min(a11))
a12<-1-(a12-min(a12))/(max(a12)-min(a12))
a13<-1-(a13-min(a13))/(max(a13)-min(a13))
a14<-1-(a14-min(a14))/(max(a14)-min(a14))
a15<-1-(a15-min(a15))/(max(a15)-min(a15))
a16<-1-(a16-min(a16))/(max(a16)-min(a16))
a17<-1-(a17-min(a17))/(max(a17)-min(a17))
a18<-1-(a18-min(a18))/(max(a18)-min(a18))
a19<-1-(a19-min(a19))/(max(a19)-min(a19))
a20<-1-(a20-min(a20))/(max(a20)-min(a20))
a21<-1-(a21-min(a21))/(max(a21)-min(a21))
a22<-1-(a22-min(a22))/(max(a22)-min(a22))
mentalhealth1<-as.matrix(a1[lower.tri(a1)])
mentalhealth2<-as.matrix(a2[lower.tri(a2)])
mentalhealth3<-as.matrix(a3[lower.tri(a3)])
mentalhealth4<-as.matrix(a4[lower.tri(a4)])
mentalhealth5<-as.matrix(a5[lower.tri(a5)])
mentalhealth6<-as.matrix(a6[lower.tri(a6)])
mentalhealth7<-as.matrix(a7[lower.tri(a7)])
mentalhealth8<-as.matrix(a8[lower.tri(a8)])
mentalhealth9<-as.matrix(a9[lower.tri(a9)])
mentalhealth10<-as.matrix(a10[lower.tri(a10)])
mentalhealth11<-as.matrix(a11[lower.tri(a11)])
mentalhealth12<-as.matrix(a12[lower.tri(a12)])
mentalhealth13<-as.matrix(a13[lower.tri(a13)])
mentalhealth14<-as.matrix(a14[lower.tri(a14)])
mentalhealth15<-as.matrix(a15[lower.tri(a15)])
mentalhealth16<-as.matrix(a16[lower.tri(a16)])
mentalhealth17<-as.matrix(a17[lower.tri(a17)])
mentalhealth18<-as.matrix(a18[lower.tri(a18)])
mentalhealth19<-as.matrix(a19[lower.tri(a19)])
mentalhealth20<-as.matrix(a20[lower.tri(a20)])
mentalhealth21<-as.matrix(a21[lower.tri(a21)])
mentalhealth22<-as.matrix(a22[lower.tri(a22)])

mentalhealth_total<-cbind(mentalhealth1,mentalhealth2,mentalhealth3,mentalhealth4,
                          mentalhealth5,mentalhealth6,mentalhealth7,mentalhealth8,
                          mentalhealth9,mentalhealth10,mentalhealth11,mentalhealth12,
                          mentalhealth13,mentalhealth14,mentalhealth15,mentalhealth16,
                          mentalhealth17,mentalhealth18,mentalhealth19,mentalhealth20,
                          mentalhealth21,mentalhealth22)
mentalhealth_totalr<-cor(mentalhealth_total,method="pearson")
pheatmap(mentalhealth_totalr,cluster_rows = FALSE, cluster_cols = FALSE,border_color = "gray",
         color = c(colorRampPalette(colors = c("#097CFF","white"))(80),
                   colorRampPalette(colors = c("white","red"))(20)),
         legend_breaks=seq(0.38,1,0.2),angle_col=45)